trigger:
- master

resources:
- repo: self

variables:
  tag: 'TestV2' 
  
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:       
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: 'steedman/testazdo'
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: steedman_dockerHub

    - task: Docker@2
      displayName: 'Push the Docker image to Dockerhub'
      inputs:
        repository: 'steedman/testazdo'
        command: 'push'
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Logout of ACR
      inputs:
        command: logout
        containerRegistry: steedman_dockerHub