# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  ImageName: 'steed/testazdo:$(Build.BuildId)'  
  
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      displayName: "List docker images"
      inputs:
        targetType: 'inline'
        script: docker images

    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: steedman_dockerHub

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

    - task: Bash@3
      displayName: "List docker images2"
      inputs:
        targetType: 'inline'
        script: docker images

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: 'steedman/testazdo'
        tags: |
          $(tag)

    - task: Bash@3
      displayName: "List docker images3"
      inputs:
        targetType: 'inline'
        script: docker images
    # - task: Docker@2
    #   displayName: Login to Docker Hub
    #   inputs:
    #     command: login
    #     containerRegistry: steedman_dockerHub

    # - task: Docker@2
    #   displayName: 'Push the Docker image to Dockerhub'
    #   inputs:
    #     # containerRegistry: 'steedman_dockerHub'
    #     repository: 'steedman/testazdo'
    #     command: 'push'
    #     tags: |
    #       $(tag)

    - task: Docker@2
      displayName: Logout of ACR
      inputs:
        command: logout
        containerRegistry: dockerRegistryServiceConnection1